question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The Earth is closest to the Sun in January.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Cats have 5 toes on their front paws.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Spiders have 6 legs.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius at sea level.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "Mickey Mouse's first appearance was in the film 'Steamboat Willie'.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "The currency of Japan is the yuan.", "answer": "False"},
    {"text": "Rabbits are rodents.", "answer": "False"},
    {"text": "The Statue of Liberty was a gift from France to the United States.", "answer": "True"},
    {"text": "The distance from the Earth to the Moon is approximately 384,400 kilometers.", "answer": "True"},
    {"text": "The fastest land animal is the cheetah.", "answer": "True"},
    {"text": "The chemical symbol for the element oxygen is O2.", "answer": "False"},
    {"text": "The human brain weighs approximately 3 pounds.", "answer": "True"},
    {"text": "The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.", "answer": "True"},
    {"text": "The longest bone in the human body is the femur.", "answer": "True"},
    {"text": "The Eiffel Tower is located in London.", "answer": "False"},
    {"text": "The moon is a satellite of the Earth.", "answer": "True"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "The first man to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"text": "The human body has four chambers in the heart.", "answer": "True"},
    {"text": "The capital of France is Berlin.", "answer": "False"},
    {"text": "The Sun is a planet.", "answer": "False"},
    {"text": "The longest river in Europe is the Danube.", "answer": "False"},
    {"text": "Diamonds are made of carbon.", "answer": "True"},
    {"text": "The scientific study of plants is called botany.", "answer": "True"},
    {"text": "The first element on the periodic table is hydrogen.", "answer": "True"},
    {"text": "The human body has four kidneys.", "answer": "False"},
    {"text": "The country with the most people in the world is China.", "answer": "True"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "The fastest bird in the world is the peregrine falcon.", "answer": "True"},
    {"text": "The first president of the United States was Thomas Jefferson.", "answer": "False"},
    {"text": "The Great Barrier Reef is located in the Atlantic Ocean.", "answer": "False"},
    {"text": "The human body has five senses.", "answer": "True"},
    {"text": "The capital of Brazil is Rio de Janeiro.", "answer": "False"},
    {"text": "The symbol 'Pb' on the periodic table stands for lead.", "answer": "True"},
    {"text": "The distance around a circle is called the diameter.", "answer": "False"},
    {"text": "The capital of Russia is Moscow.", "answer": "True"},
    {"text": "The scientific study of the Earth's atmosphere is called meteorology.", "answer": "True"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The largest planet in our solar system is Jupiter.", "answer": "True"},
    {"text": "The human body has 10 fingers.", "answer": "True"},
    {"text": "The capital of Spain is Barcelona.", "answer": "False"},
    {"text": "The symbol 'H2O' represents hydrogen dioxide.", "answer": "False"},
    {"text": "The coldest temperature ever recorded on Earth was in Antarctica.", "answer": "True"},
    {"text": "The capital of India is Mumbai.", "answer": "False"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The speed of light is approximately 300,000 kilometers per second.", "answer": "True"},
    {"text": "The country with the longest coastline in the world is Canada.", "answer": "True"},
    {"text": "The scientific study of earthquakes is called seismology.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Sn.", "answer": "False"},
    {"text": "The Amazon rainforest produces approximately 20% of the world's oxygen.", "answer": "True"},
    {"text": "The tallest building in the world is the Burj Khalifa.", "answer": "True"},
    {"text": "The capital of South Africa is Johannesburg.", "answer": "False"},
    {"text": "The chemical symbol for helium is He.", "answer": "True"},
    {"text": "The Pacific Ocean is shrinking.", "answer": "False"},
    {"text": "The human body has 12 ribs.", "answer": "True"},
    {"text": "The capital of China is Shanghai.", "answer": "False"},
    {"text": "The chemical symbol for potassium is K.", "answer": "True"},
    {"text": "The speed of sound is faster than the speed of light.", "answer": "False"},
    {"text": "The Earth's atmosphere is composed mainly of nitrogen.", "answer": "True"},
    {"text": "The currency of Brazil is the peso.", "answer": "False"},
    {"text": "The human body has three layers of skin: the epidermis, dermis, and hypodermis.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The chemical symbol for carbon dioxide is CO.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "The human body has seven vertebrae in the neck.", "answer": "True"},
    {"text": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"text": "The chemical symbol for mercury is Hg.", "answer": "True"},
    {"text": "The shortest bone in the human body is the stapes.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "The chemical symbol for calcium is Cl.", "answer": "False"},
    {"text": "The Amazon rainforest is located primarily in Brazil.", "answer": "True"},
    {"text": "The currency of Mexico is the peso.", "answer": "True"},
    {"text": "The human body has six muscles in each finger.", "answer": "False"},
    {"text": "The capital of Germany is Berlin.", "answer": "True"},
    {"text": "The chemical symbol for tin is Ti.", "answer": "False"},
    {"text": "The Amazon River flows through Brazil and Peru.", "answer": "True"},
    {"text": "The currency of the United Kingdom is the euro.", "answer": "False"},
    {"text": "The human body has four lobes in the brain.", "answer": "True"},
    {"text": "The capital of Japan is Kyoto.", "answer": "False"},
    {"text": "The chemical symbol for nitrogen is N.", "answer": "True"},
    {"text": "The Great Wall of China was built in the 14th century.", "answer": "False"},
    {"text": "The currency of China is the yen.", "answer": "False"},
    {"text": "The human body has eight cranial bones.", "answer": "False"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "The chemical symbol for magnesium is Ma.", "answer": "False"},
    {"text": "The Nile River is the longest river in the world.", "answer": "False"},
    {"text": "The currency of France is the euro.", "answer": "True"},
    {"text": "The human body has two kidneys.", "answer": "True"},
    {"text": "The capital of Turkey is Istanbul.", "answer": "False"},
    {"text": "The chemical symbol for phosphorus is P.", "answer": "True"},
    {"text": "The Sahara Desert is located in Asia.", "answer": "False"},
    {"text": "The currency of India is the rupee.", "answer": "True"},
    {"text": "The human body has three bones in the middle ear.", "answer": "True"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "The chemical symbol for uranium is Ur.", "answer": "False"},
    {"text": "The Sahara Desert is the largest desert in the world.", "answer": "True"},
    {"text": "The currency of Germany is the euro.", "answer": "True"},
    {"text": "The human body has four parathyroid glands.", "answer": "True"},
    {"text": "The capital of Australia is Canberra.", "answer": "True"},
    {"text": "The chemical symbol for silver is Si.", "answer": "False"},
    {"text": "The Sahara Desert is expanding.", "answer": "True"},
    {"text": "The currency of Switzerland is the franc.", "answer": "True"},
    {"text": "The human body has three major types of blood vessels: arteries, veins, and capillaries.", "answer": "True"},
    {"text": "The capital of Sweden is Stockholm.", "answer": "True"},
    {"text": "The chemical symbol for chlorine is Cl.", "answer": "True"},
    {"text": "The Sahara Desert is located in Africa.", "answer": "True"},
    {"text": "The currency of Russia is the euro.", "answer": "False"},
    {"text": "The human body has three main parts: the head, trunk, and limbs.", "answer": "True"},
    {"text": "The capital of Spain is Madrid.", "answer": "True"},
    {"text": "The chemical symbol for silicon is Si.", "answer": "True"},
    {"text": "The Sahara Desert is home to camels.", "answer": "True"},
    {"text": "The currency of Canada is the dollar.", "answer": "True"},
    {"text": "The human body has two lungs.", "answer": "True"},
    {"text": "The capital of Greece is Athens.", "answer": "True"},
    {"text": "The chemical symbol for gold is Gd.", "answer": "False"},
    {"text": "The Sahara Desert is bordered by the Atlantic Ocean.", "answer": "True"},
    {"text": "The currency of Egypt is the pound.", "answer": "True"},
    {"text": "The human body has two eyes.", "answer": "True"},
    {"text": "The capital of Saudi Arabia is Riyadh.", "answer": "True"},
    {"text": "The chemical symbol for helium is H.", "answer": "True"},
    {"text": "The Sahara Desert is located in the northern hemisphere.", "answer": "True"},
    {"text": "The currency of Italy is the euro.", "answer": "True"},
    {"text": "The human body has one stomach.", "answer": "False"},
    {"text": "The capital of Indonesia is Jakarta.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The Sahara Desert is the largest hot desert in the world.", "answer": "True"},
    {"text": "The currency of South Africa is the rand.", "answer": "True"},
    {"text": "The human body has five toes on each foot.", "answer": "True"},
    {"text": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"text": "The chemical symbol for potassium is K.", "answer": "True"},
    {"text": "The Sahara Desert is larger than the United States.", "answer": "False"},
    {"text": "The currency of Japan is the yen.", "answer": "True"},
    {"text": "The human body has one liver.", "answer": "True"},
    {"text": "The capital of Thailand is Bangkok.", "answer": "True"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The Sahara Desert is the hottest desert in the world.", "answer": "True"},
    {"text": "The currency of Mexico is the peso.", "answer": "True"},
    {"text": "The human body has three main types of muscles: skeletal, smooth, and cardiac.", "answer": "True"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Sahara Desert is the driest desert in the world.", "answer": "True"},
    {"text": "The currency of France is the euro.", "answer": "True"},
    {"text": "The human body has one spleen.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "The chemical symbol for mercury is Hg.", "answer": "True"},
    {"text": "The Sahara Desert is larger than Europe.", "answer": "True"},
    {"text": "The currency of India is the rupee.", "answer": "True"},
    {"text": "The human body has one pancreas.", "answer": "True"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "The chemical symbol for uranium is U.", "answer": "True"},
    {"text": "The Sahara Desert is located in Africa.", "answer": "True"},
    {"text": "The currency of Germany is the euro.", "answer": "True"},
    {"text": "The human body has two kidneys.", "answer": "True"},
    {"text": "The capital of Australia is Canberra.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Sahara Desert is expanding.", "answer": "True"},
    {"text": "The currency of Switzerland is the franc.", "answer": "True"},
    {"text": "The human body has three major types of blood vessels: arteries, veins, and capillaries.", "answer": "True"},
    {"text": "The capital of Sweden is Stockholm.", "answer": "True"},
    {"text": "The chemical symbol for chlorine is Cl.", "answer": "True"},
    {"text": "The Sahara Desert is located in Africa.", "answer": "True"},
    {"text": "The currency of Russia is the euro.", "answer": "False"},
    {"text": "The human body has three main parts: the head, trunk, and limbs.", "answer": "True"},
    {"text": "The capital of Spain is Madrid.", "answer": "True"},
    {"text": "The chemical symbol for silicon is Si.", "answer": "True"},
    {"text": "The Sahara Desert is home to camels.", "answer": "True"},
    {"text": "The currency of Canada is the dollar.", "answer": "True"},
    {"text": "The human body has two lungs.", "answer": "True"},
    {"text": "The capital of Greece is Athens.", "answer": "True"},
    {"text": "The chemical symbol for gold is Gd.", "answer": "False"},
    {"text": "The Sahara Desert is bordered by the Atlantic Ocean.", "answer": "True"},
    {"text": "The currency of Egypt is the pound.", "answer": "True"},
    {"text": "The human body has two eyes.", "answer": "True"},
    {"text": "The capital of Saudi Arabia is Riyadh.", "answer": "True"},
    {"text": "The chemical symbol for helium is H.", "answer": "True"},
    {"text": "The Sahara Desert is located in the northern hemisphere.", "answer": "True"},
    {"text": "The currency of Italy is the euro.", "answer": "True"},
    {"text": "The human body has one stomach.", "answer": "False"},
    {"text": "The capital of Indonesia is Jakarta.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The Sahara Desert is the largest hot desert in the world.", "answer": "True"},
    {"text": "The currency of South Africa is the rand.", "answer": "True"},
    {"text": "The human body has five toes on each foot.", "answer": "True"},
    {"text": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"text": "The chemical symbol for potassium is K.", "answer": "True"},
    {"text": "The Sahara Desert is larger than the United States.", "answer": "False"},
    {"text": "The currency of Japan is the yen.", "answer": "True"},
    {"text": "The human body has one liver.", "answer": "True"},
    {"text": "The capital of Thailand is Bangkok.", "answer": "True"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The Sahara Desert is the hottest desert in the world.", "answer": "True"},
    {"text": "The currency of Mexico is the peso.", "answer": "True"},
    {"text": "The human body has three main types of muscles: skeletal, smooth, and cardiac.", "answer": "True"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Sahara Desert is the driest desert in the world.", "answer": "True"},
    {"text": "The currency of France is the euro.", "answer": "True"},
    {"text": "The human body has one spleen.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"},
    {"text": "The chemical symbol for mercury is Hg.", "answer": "True"},
    {"text": "The Sahara Desert is larger than Europe.", "answer": "True"},
    {"text": "The currency of India is the rupee.", "answer": "True"},
    {"text": "The human body has one pancreas.", "answer": "True"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "The chemical symbol for uranium is U.", "answer": "True"},
    {"text": "The Sahara Desert is located in Africa.", "answer": "True"},
    {"text": "The currency of Germany is the euro.", "answer": "True"},
    {"text": "The human body has two kidneys.", "answer": "True"},
    {"text": "The capital of Australia is Canberra.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Sahara Desert is expanding.", "answer": "True"},
    {"text": "The currency of Switzerland is the franc.", "answer": "True"},
    {"text": "The human body has three major types of blood vessels: arteries, veins, and capillaries.", "answer": "True"},
    {"text": "The capital of Sweden is Stockholm.", "answer": "True"},
    {"text": "The chemical symbol for chlorine is Cl.", "answer": "True"},
    {"text": "The Sahara Desert is located in Africa.", "answer": "True"},
    {"text": "The currency of Russia is the euro.", "answer": "False"},
    {"text": "The human body has three main parts: the head, trunk, and limbs.", "answer": "True"},
    {"text": "The capital of Spain is Madrid.", "answer": "True"},
    {"text": "The chemical symbol for silicon is Si.", "answer": "True"},
    {"text": "The Sahara Desert is home to camels.", "answer": "True"},
    {"text": "The currency of Canada is the dollar.", "answer": "True"},
    {"text": "The human body has two lungs.", "answer": "True"},
    {"text": "The capital of Greece is Athens.", "answer": "True"},
    {"text": "The chemical symbol for gold is Gd.", "answer": "False"},
    {"text": "The Sahara Desert is bordered by the Atlantic Ocean.", "answer": "True"},
    {"text": "The currency of Egypt is the pound.", "answer": "True"},
    {"text": "The human body has two eyes.", "answer": "True"},
    {"text": "The capital of Saudi Arabia is Riyadh.", "answer": "True"},
    {"text": "The chemical symbol for helium is H.", "answer": "True"},
    {"text": "The Sahara Desert is located in the northern hemisphere.", "answer": "True"},
    {"text": "The currency of Italy is the euro.", "answer": "True"},
    {"text": "The human body has one stomach.", "answer": "False"},
    {"text": "The capital of Indonesia is Jakarta.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The Sahara Desert is the largest hot desert in the world.", "answer": "True"},
    {"text": "The currency of South Africa is the rand.", "answer": "True"},
    {"text": "The human body has five toes on each foot.", "answer": "True"},
    {"text": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"text": "The chemical symbol for potassium is K.", "answer": "True"},
    {"text": "The Sahara Desert is larger than the United States.", "answer": "False"},
    {"text": "The currency of Japan is the yen.", "answer": "True"},
    {"text": "The human body has one liver.", "answer": "True"},
    {"text": "The capital of Thailand is Bangkok.", "answer": "True"},
    {"text": "The chemical symbol for iron is Fe.", "answer": "True"},
    {"text": "The Sahara Desert is the hottest desert in the world.", "answer": "True"},
    {"text": "The currency of Mexico is the peso.", "answer": "True"},
    {"text": "The human body has three main types of muscles: skeletal, smooth, and cardiac.", "answer": "True"},
    {"text": "The capital of Brazil is Brasília.", "answer": "True"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The Sahara Desert is the driest desert in the world.", "answer": "True"},
    {"text": "The currency of France is the euro.", "answer": "True"},
    {"text": "The human body has one spleen.", "answer": "True"},
    {"text": "The capital of Canada is Ottawa.", "answer": "True"}
]